install:
	#pip install --upgrade pip &&\
		#pip install -r requirements.txt
lint:
	#lint using pylint
	#pylint --disable=R,C *.py
test:
	#python -m pytest -vv --cov=mylib --cov=main test_*.py
build:
	#build container
	#docker build -t deploy-wikiapi .
run:
	#run docker
	#docker run -p 8000:8000 43b96820dc2d
deploy:
	#deploy
	
